trigger:
- master

variables:
- group: RASP

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: terraform init
  displayName: 'terraform init'

- script: terraform apply -target="module.aksCluster" -auto-approve
  displayName: 'terraform apply aksCluster'

- script: terraform apply -auto-approve
  displayName: 'terraform apply'
