trigger:
- master

variables:
- group: Helix

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: terraform init
  displayName: 'terraform init'

- script: terraform apply
  displayName: 'terraform apply'
